-- v81.87 — ATS completo (Recrutamento & Seleção). Aditivo + idempotente.
alter table gp_talentos
  add column if not exists etapa text,
  add column if not exists canal text,
  add column if not exists departamento_solicitante text,
  add column if not exists vaga text,
  add column if not exists linkedin text,
  add column if not exists curriculo_url text,
  add column if not exists requisitos text,
  add column if not exists perfil_comportamental text,
  add column if not exists feedback_entrevista text,
  add column if not exists impeditivos text,
  add column if not exists cpf text,
  add column if not exists referencias text,
  add column if not exists cnd text,
  add column if not exists processos text,
  add column if not exists antecedentes text,
  add column if not exists analise_juridica text,
  add column if not exists analise_comercial text,
  add column if not exists pretensao text,
  add column if not exists disponibilidade text,
  add column if not exists score int,
  add column if not exists decisao text,
  add column if not exists motivo_reprovacao text,
  add column if not exists avaliacoes jsonb default '[]'::jsonb,
  add column if not exists historico jsonb default '[]'::jsonb;
