/* PSM-OS v2 — Código de Ética (Sprint 8.0) — 17 capítulos · 69 artigos */

const CAPITULOS = [
  { num: 1, tit: 'Princípios e Ética Profissional', intro: 'Valores essenciais: integridade, verdade, transparência e lealdade à parceria.', arts: [
    { n: '1', t: 'Compromisso com a integridade', c: 'Todo profissional parceiro da PSM deve atuar com ética, transparência e responsabilidade, mantendo conduta íntegra em qualquer situação, dentro ou fora da negociação.', m: 'Alinhamento com a liderança, advertência formal e, em casos graves ou reincidentes, encerramento da parceria e adoção de medidas legais cabíveis.' },
    { n: '2', t: 'Proibição de favorecimentos, propinas ou corrupção', c: 'É vedado qualquer tipo de benefício informal, propina, pagamento "por fora" ou tentativa de favorecer uma parte em detrimento da integridade da operação. Inclui: recebimento ou oferta de comissões não formalizadas; favorecimento em rankings, pontuação ou distribuição de leads; apoio a clientes para burlar regras internas ou evitar a intermediação da PSM.', m: 'Rescisão imediata do contrato de parceria, retenção de comissões indevidas e encaminhamento jurídico em caso de fraude ou dano à reputação da empresa.' },
    { n: '3', t: 'Fidelidade à PSM e exclusividade de atuação', c: 'Nenhum parceiro pode representar concorrentes ou atuar em nome de outras empresas utilizando estrutura, imagem, leads ou recursos vinculados à PSM.', m: 'Encerramento imediato da parceria, bloqueio de acessos, cancelamento de campanhas vinculadas e responsabilização contratual por uso indevido de estrutura institucional.' },
    { n: '4', t: 'Fraude e manipulação de dados', c: 'É proibido manipular registros, dados ou sistemas com o objetivo de se beneficiar ou distorcer a realidade das operações. Inclui: inserção de visitas falsas no CRM; alteração de datas com intenção de obter pontuação indevida; criação de grupos ou canais não autorizados para gerar vantagem competitiva.', m: 'Advertência severa, suspensão de programas de incentivo, perda de pontos e investigação interna com possível rescisão da parceria, conforme a gravidade do caso.' },
    { n: '5', t: 'Conflito de interesses', c: 'Todo parceiro deve declarar previamente qualquer envolvimento pessoal, familiar, financeiro ou comercial com imóveis, clientes ou empreendimentos relacionados à atuação imobiliária. Inclui: venda de imóvel próprio ou de familiar sem comunicação formal; participação em empreendimentos concorrentes; indicações com benefício oculto.', m: 'Advertência formal, bloqueio da negociação em andamento e, se comprovada má-fé, rescisão contratual e bloqueio de comissões.' },
    { n: '6', t: 'Uso indevido de documentos e simulações falsas', c: 'É expressamente proibido produzir ou aceitar documentos inverídicos, simulações com dados falsos ou omissões relevantes (como IPTU, condomínio, pendências judiciais).', m: 'Encerramento imediato da parceria, registro interno da infração e comunicação a órgãos legais se houver implicação jurídica.' },
    { n: '6-A', t: 'Comunicação de envolvimento jurídico relevante', c: 'Todo parceiro deve comunicar à liderança da PSM, no prazo de até 24 horas, qualquer citação, notificação judicial ou envolvimento direto em ações, inquéritos ou investigações que possam impactar sua reputação, integridade ou a imagem da empresa.', m: 'Advertência formal com registro e análise do caso pela liderança. Se houver risco reputacional ou jurídico para a empresa, poderá ocorrer bloqueio preventivo de atividades, suspensão ou rescisão contratual.' },
  ]},
  { num: 2, tit: 'Relacionamento e Ambiente Saudável', intro: 'Comportamentos esperados no convívio entre parceiros, clientes e equipe de apoio.', arts: [
    { n: '7', t: 'Respeito nas relações interpessoais', c: 'O relacionamento entre parceiros da PSM deve ser pautado por respeito, empatia, colaboração e comunicação assertiva. Atitudes como fofoca, isolamento intencional, hostilidade, rivalidade desleal ou comentários depreciativos sobre colegas são incompatíveis com a cultura da empresa.', m: 'Advertência formal, mediação com a liderança e, se houver reincidência ou impacto coletivo, reavaliação da permanência na parceria.' },
    { n: '8', t: 'Prevenção e enfrentamento de assédio ou preconceito', c: 'Não são toleradas condutas de assédio, discriminação ou preconceito, seja por parte de colegas, clientes, fornecedores ou terceiros. Inclui comentários ofensivos, conotação sexual, abordagens invasivas, constrangimento físico ou verbal, ou qualquer forma de exclusão.', m: 'Encaminhamento imediato à liderança, suporte à vítima, registro interno e, nos casos aplicáveis, encerramento da parceria e medidas legais.' },
    { n: '9', t: 'Comunicação respeitosa em todos os canais', c: 'A comunicação com colegas, clientes, prestadores ou membros da equipe de apoio deve ser sempre respeitosa, mesmo diante de conflitos ou frustrações. É proibido usar grupos oficiais para expor críticas, ironias, indiretas ou provocar constrangimento.', m: 'Advertência formal, conversa direta com a liderança e acompanhamento da conduta.' },
    { n: '10', t: 'Conduta em situações de conflito', c: 'Conflitos sobre atendimentos, captações, leads ou clientes devem ser resolvidos com diálogo direto, empatia e, se necessário, com mediação da liderança. É proibido espalhar boatos ou adotar posturas hostis.', m: 'Mediação formal com registro interno e advertência em caso de conduta desrespeitosa ou recorrente.' },
    { n: '11', t: 'Respeito à equipe de apoio', c: 'Nenhum parceiro deve tratar com agressividade ou desrespeito os membros da equipe administrativa, operacional, jurídica, de marketing ou qualquer outro setor de suporte da PSM.', m: 'Mediação com liderança, orientação formal e possível restrição de suporte ou recursos.' },
  ]},
  { num: 3, tit: 'Relacionamentos Pessoais', intro: 'Condução ética e transparente de vínculos afetivos no ambiente profissional.', arts: [
    { n: '12', t: 'Relacionamentos afetivos entre parceiros da PSM', c: 'Relacionamentos afetivos ou íntimos entre profissionais parceiros devem ser comunicados à liderança assim que estabelecidos, visando a prevenção de conflitos de interesse, favorecimentos ou impactos no ambiente da equipe.', m: 'Alerta formal com registro, acompanhamento da liderança e, se necessário, redistribuição de atendimentos ou reavaliação de alocação de plantões.' },
    { n: '13', t: 'Relacionamento com clientes ativos', c: 'Envolvimentos afetivos com clientes que estejam em atendimento ativo devem ser imediatamente informados à liderança, a fim de evitar situações de influência, conflito de interesse ou quebra de confiança profissional.', m: 'Análise interna, redistribuição do atendimento, eventual bloqueio do lead e registro do caso.' },
  ]},
  { num: 4, tit: 'Imagem Profissional e Apresentação Pessoal', intro: 'Padrões de imagem, postura e apresentação alinhados à identidade da PSM.', arts: [
    { n: '14', t: 'Vestimenta e aparência profissional', c: 'A imagem dos parceiros da PSM deve refletir sobriedade, organização e coerência com o ambiente de trabalho. Recomenda-se estilo casual básico, com roupas limpas, bem-cuidadas e sem excessos. São vedadas peças inadequadas, como moletom, chinelo, boné, óculos escuros em ambiente interno, sandálias rasteiras, roupas curtas, camisetas de incorporadoras ou com estampas polêmicas.', m: 'Advertência leve, orientação direta sobre imagem profissional e, em casos de repetição, limitação da participação em ações presenciais.' },
    { n: '15', t: 'Postura e conduta visual nos ambientes PSM', c: 'A postura visual do parceiro — incluindo cuidados com higiene, apresentação pessoal, linguagem corporal e tom de voz — deve estar alinhada com a experiência de excelência que a PSM busca transmitir.', m: 'Feedback individual com registro de orientação e, em casos de impacto direto na reputação da marca, acompanhamento formal.' },
  ]},
  { num: 5, tit: 'Atendimento ao Cliente', intro: 'Princípios e padrões de excelência no relacionamento com clientes.', arts: [
    { n: '16', t: 'Atendimento com igualdade e excelência', c: 'Todos os clientes devem ser atendidos com o mesmo padrão de dedicação, cortesia e profissionalismo, independentemente do valor do imóvel, do canal de origem ou do seu perfil pessoal.', m: 'Feedback individual, perda de pontos em programas internos e, em casos recorrentes, bloqueio de leads.' },
    { n: '17', t: 'Compromisso com horários e pontualidade', c: 'O não comparecimento a visitas ou reuniões sem aviso prévio ao cliente ou à equipe compromete a imagem da PSM. É dever do parceiro respeitar os compromissos assumidos.', m: 'Advertência formal, perda de pontos e possível restrição em plantões ou repasses.' },
    { n: '18', t: 'Continuidade e responsabilidade no atendimento', c: 'Nenhum cliente pode ser deixado desassistido. Em caso de ausência temporária ou necessidade de afastamento, o parceiro deve comunicar a liderança com antecedência.', m: 'Advertência com registro, realocação supervisionada do cliente e possível bloqueio de novas oportunidades.' },
    { n: '19', t: 'Respeito à escolha do cliente e ao trabalho dos colegas', c: 'É direito do cliente decidir com qual profissional deseja negociar. Nenhum parceiro deve criticar, influenciar negativamente ou desmerecer outro colega.', m: 'Advertência com registro, aconselhamento individual e, em caso de reincidência, avaliação ética da permanência.' },
    { n: '20', t: 'Abordagem em situações de retorno de cliente', c: 'Se um cliente retornar após ter sido oficialmente descartado, o atendimento poderá ser assumido livremente. Se o cliente estiver em atendimento ativo, deve-se respeitar o vínculo vigente, evitando qualquer tentativa de apropriação.', m: 'Mediação com registro interno e validação do atendimento ativo de forma justa para ambas as partes.' },
    { n: '21', t: 'Troca de responsável por atendimento', c: 'A substituição ou retirada de um parceiro de um atendimento somente poderá ocorrer com consentimento da liderança e comunicação clara, tanto ao colega quanto ao cliente.', m: 'Advertência formal e mediação com a liderança.' },
    { n: '21-A', t: 'Preenchimento da ficha de atendimento', c: 'É obrigação do parceiro preencher a ficha de atendimento de forma completa, precisa e atualizada, a fim de assegurar rastreabilidade, continuidade e registro formal.', m: 'Advertência com registro formal, bloqueio de leads até regularização e acompanhamento da reincidência.' },
  ]},
  { num: 6, tit: 'Visitas e Acesso aos Imóveis', intro: 'Condições para agendamento, realização e registro de visitas.', arts: [
    { n: '22', t: 'Visitas somente com autorização formal', c: 'Nenhuma visita pode ser realizada sem autorização expressa do proprietário, responsável legal ou parceiro autorizado. Visitas em imóveis com bloqueio judicial, pendência contratual ou impedimento legal são terminantemente proibidas.', m: 'Advertência severa, perda de pontos e, conforme a gravidade, rescisão da parceria.' },
    { n: '23', t: 'Agendamento com respeito à disponibilidade do imóvel', c: 'Visitas a imóveis ocupados, com inquilinos ou proprietários presentes, devem ser agendadas com no mínimo 24 horas de antecedência.', m: 'Alinhamento formal, advertência e, em caso de reincidência, suspensão temporária da autonomia em agendamentos.' },
    { n: '24', t: 'Acesso compartilhado e colaboração entre parceiros', c: 'Imóveis compartilhados devem ter acesso justo entre os parceiros autorizados. É proibido bloquear, omitir ou dificultar propositalmente o acesso de outros colegas.', m: 'Advertência com registro e, em caso de conduta reincidente, suspensão da autorização de uso do imóvel e responsabilização formal.' },
    { n: '25', t: 'Devolução imediata das chaves', c: 'As chaves utilizadas em visita devem ser devolvidas logo após o uso, respeitando os combinados. Alíneas: a) Quem perde a chave arca com custos; b) Danos causados devem ser pagos; c) Retirada com terceiros exige autorização; d) Controle de chaves com registro e assinatura.', m: 'Advertência com responsabilização formal, perda de pontos e restrição de novos acessos.' },
    { n: '25-B', t: 'Preparação e cuidado com salas de reunião', c: 'É responsabilidade do parceiro preparar a sala de reunião antes do uso e garantir sua organização após o término.', m: 'Advertência formal e restrição temporária ao uso de salas em caso de descuido reincidente.' },
    { n: '26', t: 'Registro correto de visitas realizadas', c: 'Somente visitas reais e efetivamente realizadas devem ser registradas no CRM. É vedado lançar visitas fictícias, adiantar registros ou alterar datas para obter vantagem.', m: 'Desclassificação imediata de rankings, advertência formal, perda de pontos e possível exclusão de programas de incentivo.' },
  ]},
  { num: 7, tit: 'CRM e Registro de Atividades', intro: 'Diretrizes para uso correto do CRM e demais sistemas da PSM.', arts: [
    { n: '27', t: 'Registro completo e fiel das atividades', c: 'Todo atendimento, visita ou movimentação relevante deve ser registrado no CRM oficial da PSM. Omissões frequentes, dados incompletos ou falhas intencionais comprometem o controle dos processos.', m: 'Advertência formal, reforço sobre o uso correto do sistema e, em caso de reincidência, bloqueio de leads e suspensão de repasses automáticos.' },
    { n: '28', t: 'Proibição de lançamentos fictícios ou manipulados', c: 'É proibido lançar visitas não realizadas, alterar datas para subir em rankings, duplicar registros ou usar o sistema para gerar vantagem indevida.', m: 'Advertência severa, perda de pontos, exclusão imediata de campanhas e análise para possível rescisão contratual.' },
    { n: '29', t: 'Acesso pessoal e intransferível', c: 'Os acessos à plataforma, senhas e logins são de uso exclusivo e individual. Compartilhar credenciais é estritamente proibido.', m: 'Corte imediato de acesso, advertência formal, reavaliação do vínculo e encaminhamento para medidas judiciais em caso de violação à LGPD.' },
    { n: '30', t: 'Atualização regular de negócios e dados', c: 'Todos os negócios ativos no CRM devem ser atualizados com frequência. Negócios abandonados ou dados desatualizados prejudicam o fluxo operacional.', m: 'Advertência, perda de prioridade em distribuição de leads e suspensão de acesso temporário.' },
  ]},
  { num: 8, tit: 'Divulgação e Comunicação de Imóveis', intro: 'Diretrizes para uso de imagens, materiais de divulgação e identidade visual.', arts: [
    { n: '31', t: 'Uso responsável da identidade visual', c: 'Todo material de divulgação deve respeitar o padrão visual oficial da PSM, com uso correto de logotipo, cores, fontes e formatos definidos.', m: 'Advertência, exigência de correção imediata e, em caso de reincidência, suspensão temporária de publicações.' },
    { n: '32', t: 'Autorização prévia para publicação de imóveis', c: 'A publicação de qualquer imóvel só é permitida após entrega de toda documentação obrigatória, autorização formal do proprietário e validação interna.', m: 'Advertência formal, bloqueio da publicação e, em caso de risco jurídico, análise contratual.' },
    { n: '33', t: 'Qualidade e veracidade das imagens', c: 'Todas as imagens usadas nas divulgações devem ser reais, atuais e representar fielmente o imóvel. É proibido o uso de fotos desatualizadas, retocadas em excesso ou com distorção.', m: 'Advertência com exigência de nova padronização, refação da publicação e perda de pontos.' },
    { n: '34', t: 'Respeito à privacidade em fotografias', c: 'É proibido fotografar imóveis com objetos ou pertences pessoais do morador sem autorização. Também é vedado divulgar imagens de clientes, parceiros ou terceiros sem consentimento formal.', m: 'Advertência, obrigação de remoção do conteúdo e, em caso de reincidência, encaminhamento jurídico conforme LGPD.' },
    { n: '35', t: 'Produção de conteúdo audiovisual em imóveis', c: 'Lives, vídeos ou gravações em imóveis exigem autorização prévia do proprietário, mesmo que o conteúdo seja usado apenas em redes sociais.', m: 'Advertência e retirada imediata do conteúdo publicado, com possibilidade de bloqueio para ações de mídia.' },
  ]},
  { num: 9, tit: 'Captação e Exclusividades', intro: 'Princípios éticos no processo de captação de imóveis.', arts: [
    { n: '36', t: 'Respeito à exclusividade de captação', c: 'Captações com exclusividade vigente por outra imobiliária ou corretor devem ser respeitadas. É proibido tentar burlar ou anular uma exclusividade sem autorização expressa.', m: 'Advertência, bloqueio da captação irregular e, em caso de reincidência, avaliação contratual.' },
    { n: '37', t: 'Proibição de copiar anúncios ou usar materiais de colegas', c: 'É vedado copiar publicações, descrições, imagens, textos ou qualquer material criado por outro parceiro sem consentimento explícito.', m: 'Advertência, perda de pontos e, se houver má-fé, suspensão da parceria ou exclusão da captação.' },
    { n: '38', t: 'Origem e transparência nas captações', c: 'Toda captação deve ter origem legítima e transparente. É proibido induzir o proprietário a romper exclusividade com outra imobiliária ou ocultar o vínculo com a PSM.', m: 'Advertência formal, bloqueio da captação e, em caso de violação grave, rescisão imediata da parceria.' },
  ]},
  { num: 10, tit: 'Confidencialidade e Proteção de Dados', intro: 'Uso, proteção e sigilo de informações — LGPD.', arts: [
    { n: '39', t: 'Proteção de dados e informações sensíveis', c: 'É dever do parceiro proteger todas as informações recebidas em razão da atuação na PSM, incluindo dados de clientes, contratos, valores, documentos, prints e propostas.', m: 'Advertência formal, reeducação ética, bloqueio de acessos e, em casos graves, rescisão e encaminhamento jurídico conforme LGPD.' },
    { n: '40', t: 'Compartilhamento de conteúdo com terceiros', c: 'É proibido compartilhar qualquer tipo de conteúdo — como propostas, prints de conversas, dados cadastrais ou documentos — com pessoas não diretamente envolvidas.', m: 'Advertência formal, registro em ata e rebaixamento de nível em programas de pontuação.' },
    { n: '41', t: 'Uso de imagens e identidade de clientes ou parceiros', c: 'Imagens, vídeos, nomes, mensagens ou qualquer dado que identifique um cliente, parceiro ou colaborador só podem ser divulgados com autorização expressa, de acordo com a LGPD.', m: 'Advertência com retirada imediata do conteúdo e, em reincidência, avaliação contratual.' },
    { n: '42', t: 'Acesso indevido a informações restritas', c: 'É proibido acessar documentos, contratos ou registros confidenciais que não estejam diretamente relacionados à função ou ao atendimento em curso.', m: 'Corte imediato de acesso, advertência formal e, em casos graves, rescisão contratual por quebra de sigilo.' },
  ]},
  { num: 11, tit: 'Comunicação Institucional', intro: 'Comunicação dentro dos ambientes oficiais e conduta em ambientes públicos/digitais.', arts: [
    { n: '43', t: 'Críticas e feedbacks à gestão', c: 'Críticas à empresa, à liderança ou aos processos internos devem ser feitas exclusivamente por canais institucionais apropriados, de forma respeitosa e construtiva.', m: 'Advertência formal, conversa direta com a liderança e, em reincidência, suspensão de programas de incentivo.' },
    { n: '44', t: 'Postura em grupos oficiais e canais de comunicação', c: 'É vedado apagar mensagens para esconder informações, utilizar tom sarcástico ou desrespeitoso, ou criar grupos paralelos.', m: 'Advertência, registro em ata e perda de pontos. Em caso de manipulação, rebaixamento de comissão ou rescisão.' },
    { n: '45', t: 'Uso da imagem e nome da PSM em redes sociais', c: 'Todo conteúdo que envolva a marca PSM deve ser aprovado pela liderança. O parceiro não deve utilizar logotipo próprio. O padrão é nome completo com número de CRECI e identidade oficial PSM.', m: 'Advertência com exigência de correção ou retirada e restrição temporária de uso da marca.' },
    { n: '45-A', t: 'Canais oficiais de comunicação', c: 'Toda comunicação profissional deve ser feita exclusivamente pelos canais autorizados pela PSM (e-mail institucional e WhatsApp corporativo). É vedado o uso de e-mail pessoal.', m: 'Advertência formal e, em reincidência, bloqueio do lead e suspensão de novas oportunidades.' },
  ]},
  { num: 12, tit: 'Contratos, Propostas e Formalizações', intro: 'Regras para elaboração, envio e gestão de propostas, contratos e reservas.', arts: [
    { n: '46', t: 'Formalização obrigatória de negociações', c: 'Toda negociação deve ser formalizada por escrito, com documentação completa e comunicação à liderança. É proibido aceitar pagamentos informais ou realizar tratativa "por fora".', m: 'Advertência severa, bloqueio da negociação, perda de comissão e medidas judiciais cabíveis.' },
    { n: '47', t: 'Propostas reais, completas e autorizadas', c: 'Propostas comerciais devem conter todas as condições reais e válidas, com consentimento claro do cliente.', m: 'Advertência formal, retratação com o cliente, bloqueio da proposta e encaminhamento jurídico em caso de fraude.' },
    { n: '48', t: 'Assinatura digital e procedimentos com imóveis de terceiros', c: 'Contratos de imóveis de terceiros ou repasse devem ser elaborados exclusivamente pelo escritório jurídico parceiro e enviados para assinatura digital pelo login institucional.', m: 'Advertência formal, invalidação do contrato, perda de comissão e, em fraude, responsabilização cível e criminal.' },
    { n: '48-A', t: 'Propostas paralelas e negociações externas', c: 'É expressamente proibido elaborar ou conduzir propostas fora dos canais institucionais da PSM, mesmo que iniciado por fora.', m: 'Advertência formal, bloqueio da negociação, perda de comissão e responsabilização contratual e jurídica.' },
    { n: '49', t: 'Procedimentos em imóveis adquiridos junto à incorporadora', c: 'É responsabilidade do parceiro manter a PSM informada durante todas as etapas. Cópias dos contratos devem ser compartilhadas com a PSM.', m: 'Advertência, bloqueio de leads e, em ocultação, revisão contratual imediata.' },
    { n: '49-A', t: 'Documentação completa nas propostas', c: 'O envio de propostas deve estar sempre acompanhado da documentação completa do cliente, incluindo documentos pessoais, comprovantes e, quando aplicável, certidões negativas.', m: 'Advertência formal, bloqueio da proposta e responsabilização em caso de prejuízo.' },
    { n: '50', t: 'Alterações contratuais e cláusulas não autorizadas', c: 'Nenhuma cláusula pode ser incluída, modificada ou omitida sem validação expressa da liderança ou do jurídico.', m: 'Invalidação do contrato, advertência severa e revalidação junto ao cliente.' },
    { n: '51', t: 'Confirmação da intermediação e vínculo com a PSM', c: 'A intermediação da PSM deve estar expressa e formalizada em todos os documentos. Qualquer tentativa de omitir é considerada grave violação ética.', m: 'Rescisão imediata, retenção de comissão e responsabilização por perdas e danos.' },
  ]},
  { num: 13, tit: 'Comissões e Remuneração', intro: 'Regras para recebimento de comissões, proibições de acordos informais.', arts: [
    { n: '52', t: 'Proibição de comissões informais ou "por fora"', c: 'É terminantemente proibido oferecer, aceitar ou negociar comissões não registradas formalmente, incluindo com seguradoras, administradoras, corretores de seguro, consórcio ou advogados.', m: 'Rescisão imediata, retenção de valores, bloqueio de comissão e responsabilização contratual e jurídica.' },
    { n: '53', t: 'Divulgação inadequada de ganhos ou comissões', c: 'É proibido compartilhar prints, valores recebidos ou demonstrar ganhos em ambientes informais ou redes sociais.', m: 'Advertência formal, rebaixamento em programas e restrição de participação em campanhas.' },
    { n: '54', t: 'Alterações em valores ou porcentagens de comissão', c: 'Nenhuma alteração em comissões ou tabelas pode ser realizada sem aprovação da liderança.', m: 'O corretor assume integralmente o compromisso, ônus e perdas, além de perder o direito à comissão original.' },
    { n: '55', t: 'Comissão em imóveis próprios ou de familiares', c: 'Parceiros que vendem imóveis próprios ou de familiares devem declarar formalmente à liderança antes da divulgação.', m: 'Advertência formal, bloqueio da comissão, revisão da negociação e, em omissão intencional, rescisão.' },
    { n: '55-A', t: 'Comissão entre corretores parceiros', c: 'A divisão de comissão entre parceiros deve ser previamente alinhada e comunicada à liderança, sendo vedados acordos verbais.', m: 'Advertência formal e, em impasse, retenção temporária da comissão até regularização.' },
  ]},
  { num: 14, tit: 'Parcerias e Indicações', intro: 'Conduta ética na indicação de prestadores de serviço e relacionamento com parceiros externos.', arts: [
    { n: '56', t: 'Indicações com isenção e responsabilidade', c: 'Ao indicar prestadores, o parceiro deve agir com isenção, focando no interesse do cliente. É proibido trocar favores, aceitar comissões ocultas ou condicionar atendimento.', m: 'Advertência formal, rompimento da parceria com o prestador e, em reincidência, rescisão.' },
    { n: '57', t: 'Exclusividades e acordos com terceiros', c: 'Exclusividades ou parcerias com terceiros só têm validade se formalizadas por contrato reconhecido pela PSM. Nenhum parceiro está autorizado a assinar institucionalmente.', m: 'Advertência formal e, em prejuízo, responsabilização legal por falsa representação.' },
    { n: '57-A', t: 'Atuação sem CRECI ativo', c: 'É proibido atuar na intermediação imobiliária sem registro válido no CRECI. Caso suspenso ou vencido, deve comunicar imediatamente.', m: 'Suspensão imediata das atividades e, em atuação sem habilitação, aplicação de multa e rescisão contratual.' },
    { n: '58', t: 'Solicitações e ações junto a parceiros externos', c: 'Qualquer solicitação feita em nome da PSM a parceiros externos deve ser previamente alinhada com a liderança e registrada no CRM.', m: 'Advertência, bloqueio temporário de acessos e realinhamento estratégico.' },
    { n: '58-A', t: 'Participação em serviços ou contratações externas', c: 'O parceiro não deve se envolver diretamente na contratação de reformas, manutenção, obras ou serviços em nome do cliente.', m: 'Advertência formal e responsabilização direta por qualquer prejuízo causado.' },
  ]},
  { num: 15, tit: 'Infraestrutura e Recursos', intro: 'Uso dos recursos físicos, digitais e operacionais da PSM.', arts: [
    { n: '59', t: 'Uso adequado dos recursos da empresa', c: 'Recursos como veículos, computadores, impressoras, sistemas, salas e materiais são de uso exclusivo para fins profissionais vinculados à PSM.', m: 'Advertência formal, corte de acesso e, em prejuízo, responsabilização contratual com ressarcimento.' },
    { n: '60', t: 'Preservação e organização dos ambientes', c: 'É dever de todos manter os espaços físicos organizados, limpos e em condições adequadas de uso.', m: 'Advertência leve, orientação imediata e, em danos, reposição ou indenização proporcional.' },
    { n: '60-A', t: 'Proibição de recebimento de correspondência', c: 'É terminantemente proibido utilizar o endereço da PSM para recebimento de correspondências pessoais ou comerciais.', m: 'Advertência formal e, em reincidência, bloqueio temporário de acesso ao escritório.' },
    { n: '61', t: 'Acesso e senhas pessoais', c: 'Todos os acessos fornecidos pela PSM — logins, senhas, usuários — são de uso individual e intransferível.', m: 'Corte imediato do acesso, advertência, rescisão em caso de violação grave e encaminhamento jurídico por quebra de sigilo.' },
    { n: '62', t: 'Permanência em canais oficiais', c: 'Todos os parceiros devem permanecer nos grupos oficiais de comunicação e nos canais operacionais ativos, salvo autorização expressa.', m: 'Advertência com alinhamento formal e suspensão temporária em campanhas.' },
  ]},
  { num: 16, tit: 'Responsabilidades em Representação da Marca', intro: 'Comportamento esperado ao atuar em nome da PSM.', arts: [
    { n: '63', t: 'Lealdade na representação da PSM', c: 'Ao atuar sob a bandeira da PSM, o parceiro assume o compromisso de defender a integridade da marca. É proibido sugerir que o cliente "negocie por fora" para evitar comissão ou omitir a participação da empresa.', m: 'Rescisão imediata, cobrança da comissão devida, bloqueio de acesso e responsabilização por perdas e danos.' },
    { n: '64', t: 'Conduta em atendimentos externos e eventos', c: 'A postura do parceiro em eventos, visitas, plantões, reuniões externas e redes sociais deve refletir os valores e o profissionalismo da PSM.', m: 'Advertência formal, exclusão de escalas ou eventos futuros e acompanhamento individual.' },
    { n: '65', t: 'Uso responsável da imagem da empresa', c: 'É vedado usar o nome, logotipo, campanhas, identidade visual ou materiais da PSM para ações individuais ou conteúdo pessoal não autorizado.', m: 'Advertência com obrigação de correção, bloqueio do uso de marca e revisão do vínculo.' },
  ]},
  { num: 17, tit: 'Penalidades Finais e Procedimentos de Encerramento', intro: 'Critérios para aplicação de penalidades e procedimentos formais.', arts: [
    { n: '66', t: 'Escalonamento de consequências', c: 'As medidas corretivas seguem o princípio da proporcionalidade: feedback verbal, advertência leve, advertência formal, suspensão de campanhas, bloqueio de acesso, perda de pontos, mediação, corte de comissão e rescisão.', m: 'A liderança tem autonomia para aplicar as medidas conforme cada caso, com registro e comunicação direta.' },
    { n: '67', t: 'Fatos que configuram rescisão imediata da parceria', c: 'Motivos diretos para encerramento imediato sem advertência prévia: tentativa de fraude, corrupção, "por fora", quebra de sigilo, uso indevido da estrutura, assédio, preconceito, desvio de cliente, documentos falsos, manipulação intencional.', m: 'Rescisão contratual imediata, bloqueio de comissões, exclusão de campanhas, registro e adoção de medidas judiciais.' },
    { n: '68', t: 'Encerramento por alinhamento cultural', c: 'A parceria poderá ser encerrada quando identificado desalinhamento de valores, baixa adesão às diretrizes ou comportamento incompatível com a cultura PSM.', m: 'Alinhamento com a liderança, registro de histórico e formalização do encerramento.' },
    { n: '69', t: 'Processo de comunicação e registro das medidas', c: 'Toda ação corretiva será comunicada ao parceiro de forma direta, com registro no sistema interno. Em casos relevantes, será solicitado aceite formal do termo de ciência.', m: 'Aplicação do processo formal de desligamento com base no contrato de parceria vigente.' },
  ]},
];

export async function pageEtica(ctx, root) {
  const totalArts = CAPITULOS.reduce((s, c) => s + c.arts.length, 0);
  root.innerHTML = `
    <div class="card">
      <div style="background:linear-gradient(135deg, #0b1f3a 0%, #1e3a5f 100%);color:#fff;padding:24px;border-radius:12px;margin-bottom:20px">
        <h2 style="margin:0;font-size:24px;font-weight:900">⚖️ Código de Ética PSM Imóveis</h2>
        <p style="margin:4px 0 0;opacity:.8;font-size:13px">${CAPITULOS.length} Capítulos · ${totalArts} Artigos · Conduta profissional obrigatória</p>
      </div>

      <div style="background:var(--bg-3);border-radius:10px;padding:14px 18px;margin-bottom:18px">
        <div style="font-weight:800;color:var(--psm-gold);margin-bottom:8px">📑 Sumário</div>
        <ol style="margin:0;padding-left:22px;line-height:1.9;font-size:13px">
          ${CAPITULOS.map(c => `<li><a href="#cap-${c.num}" style="color:var(--tx);text-decoration:none">${esc(c.tit)}</a></li>`).join('')}
        </ol>
      </div>

      ${CAPITULOS.map(cap => `
        <div id="cap-${cap.num}" style="margin:22px 0;padding-top:12px;border-top:2px solid var(--psm-gold)">
          <h3 style="color:var(--psm-gold);font-size:17px;font-weight:900;margin:0 0 4px">CAPÍTULO ${cap.num} — ${esc(cap.tit)}</h3>
          <div class="tiny muted" style="font-style:italic;margin-bottom:12px">${esc(cap.intro)}</div>
          ${cap.arts.map(a => `
            <div style="background:var(--bg-3);border-left:4px solid var(--psm-gold);border-radius:8px;padding:12px 16px;margin-bottom:10px">
              <div style="font-weight:800;margin-bottom:6px">Art. ${esc(a.n)} — ${esc(a.t)}</div>
              <div style="font-size:13px;line-height:1.6;margin-bottom:8px">${esc(a.c)}</div>
              <div style="background:#fef3c7;color:#78350f;border-left:3px solid #f59e0b;padding:8px 12px;border-radius:6px;font-size:12px">
                <b>⚠️ Consequência:</b> ${esc(a.m)}
              </div>
            </div>
          `).join('')}
        </div>
      `).join('')}

      <div style="background:linear-gradient(135deg,#fef3c7,#fde68a);color:#78350f;border-radius:10px;padding:14px 18px;margin-top:20px;text-align:center;font-weight:600">
        Este código é parte integrante do contrato de parceria. O descumprimento pode acarretar nas consequências descritas em cada artigo.
      </div>

      <div class="mt-4 flex gap-2 no-print" style="flex-wrap:wrap">
        <button class="btn btn-primary" onclick="window.print()">🖨 Imprimir / Salvar PDF</button>
        <button class="btn btn-ghost" data-nav="/manual">📖 Voltar ao Manual</button>
        <button class="btn btn-ghost" data-nav="/base">📚 Base de Conhecimento</button>
      </div>
    </div>
  `;
  root.querySelectorAll('[data-nav]').forEach(b => b.addEventListener('click', () => { location.hash = b.dataset.nav; }));
}

function esc(s) { return String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
