const properties = [
  // Category 1: Repasse Imediato | Minha Casa Minha Vida (PSM CONQUISTA)
  {
    id: 1,
    nome: "UNIQUE PALESTRA",
    incorporadora: "INC",
    regiao: "OESTE",
    m2: 32.96,
    valor: 184800,
    valor_avaliacao: 233024,
    entrega: "04/2028",
    dorms: 1,
    condicao: "Financiamento Imediato Parcelamento 60x (incc/ipca+2%)",
    renda_ideal: "2850-3500",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 2,
    nome: "UNIQUE PALESTRA",
    incorporadora: "INC",
    regiao: "OESTE",
    m2: 33,
    valor: 199900,
    valor_avaliacao: 234024,
    entrega: "04/2028",
    dorms: 1,
    condicao: "Financiamento Imediato Parcelamento 60x (incc/ipca+2%)",
    renda_ideal: "2850-3500",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 3,
    nome: "UNIQUE PALESTRA",
    incorporadora: "INC",
    regiao: "OESTE",
    m2: 29,
    valor: 184800,
    valor_avaliacao: 200396,
    entrega: "04/2028",
    dorms: 1,
    condicao: "Financiamento Imediato Parcelamento 60x (incc/ipca+2%)",
    renda_ideal: "2850-3500",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 4,
    nome: "UNIQUE PALESTRA",
    incorporadora: "INC",
    regiao: "OESTE",
    m2: 35.9,
    valor: 189900,
    valor_avaliacao: 233322,
    entrega: "04/2028",
    dorms: 1,
    condicao: "Financiamento Imediato Parcelamento 60x (incc/ipca+2%)",
    renda_ideal: "2850-3500",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 5,
    nome: "CASA UNICOS FLOR DO CAMPO",
    incorporadora: "UNICOS",
    regiao: "MIRASOL",
    m2: null,
    valor: 190000,
    valor_avaliacao: 220000,
    entrega: null,
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "3500-3800",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 6,
    nome: "RESIDENCIAL JARDIM DAS OLIVEIRAS",
    incorporadora: "MRV",
    regiao: "NORTE",
    m2: null,
    valor: 210190,
    valor_avaliacao: 224300,
    entrega: null,
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "3700-4000",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 7,
    nome: "VILA HARMONIA",
    incorporadora: "RVE",
    regiao: "NORTE",
    m2: 39.5,
    valor: 225000,
    valor_avaliacao: 264000,
    entrega: "11/2027",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "4700",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 8,
    nome: "SOLIS",
    incorporadora: "LONGITUDE",
    regiao: "MIRASSOL",
    m2: 39.1,
    valor: 194000,
    valor_avaliacao: 220000,
    entrega: "10/2027",
    dorms: 2,
    condicao: "Financiamento Imediato ENTRADA EM ATÃ 100X + DOC GRATIS",
    renda_ideal: "3500-3800",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 9,
    nome: "ECO VIVA - MAIS PARQUE",
    incorporadora: "EMAIS",
    regiao: "LESTE",
    m2: 44.4,
    valor: 214500,
    valor_avaliacao: 243000,
    entrega: "11/2027",
    dorms: 2,
    condicao: "Financiamento Imediato ENTRADA ATÃ 90X",
    renda_ideal: "4500",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 10,
    nome: "ECO VIVA - MAIS PARQUE",
    incorporadora: "EMAIS",
    regiao: "LESTE",
    m2: 54,
    valor: 247500,
    valor_avaliacao: 264000,
    entrega: "11/2027",
    dorms: 2,
    condicao: "Financiamento Imediato ENTRADA ATE 90X DOC GRÃTIS",
    renda_ideal: "4500",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 11,
    nome: "PARQUE RIO GRANDENA",
    incorporadora: "MRV",
    regiao: "LESTE",
    m2: 39.3,
    valor: 255490,
    valor_avaliacao: 279000,
    entrega: "02/2027",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "5800",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 12,
    nome: "RESIDENCIAL TREVISO",
    incorporadora: "FAJ",
    regiao: "BADY BASSIT",
    m2: 44.0,
    valor: 216900,
    valor_avaliacao: 220000,
    entrega: null,
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "4700",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 13,
    nome: "RESIDENCIAL VETORASSO",
    incorporadora: "FAJ",
    regiao: "NORTE",
    m2: 44.0,
    valor: 219900,
    valor_avaliacao: 240000,
    entrega: null,
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "4200",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 14,
    nome: "VILA HARMONIA",
    incorporadora: "RVE",
    regiao: "NORTE",
    m2: 42.4,
    valor: 225000,
    valor_avaliacao: 264000,
    entrega: "11/2027",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "4700",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 15,
    nome: "ECO VIVA - VISTA BELA",
    incorporadora: "EMAIS",
    regiao: "OESTE",
    m2: 44.4,
    valor: 218170,
    valor_avaliacao: 264000,
    entrega: "11/2027",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "4700",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 16,
    nome: "ECO VIVA - MAIS PARQUE",
    incorporadora: "EMAIS",
    regiao: "LESTE",
    m2: 49.9,
    valor: 225900,
    valor_avaliacao: 264000,
    entrega: "11/2027",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "4500",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 17,
    nome: "TREND",
    incorporadora: "LONGITUDE",
    regiao: "NORTE",
    m2: 41.0,
    valor: 239900,
    valor_avaliacao: 264000,
    entrega: "01/2028",
    dorms: 2,
    condicao: "Financiamento Imediato ENTRADA ATÃ 82X DOC GRATIS",
    renda_ideal: "4700",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 18,
    nome: "PARQUE SORRENTO",
    incorporadora: "MRV",
    regiao: "NORTE",
    m2: 39.3,
    valor: 247990,
    valor_avaliacao: 289700,
    entrega: "02/2027",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "6000",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 19,
    nome: "PARQUE RIO PORTUGAL",
    incorporadora: "MRV",
    regiao: "SUL",
    m2: 39.3,
    valor: 256500,
    valor_avaliacao: 262000,
    entrega: "ENTREGUE",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "4700",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 20,
    nome: "TREND",
    incorporadora: "LONGITUDE",
    regiao: "NORTE",
    m2: 41.9,
    valor: 262000,
    valor_avaliacao: 262000,
    entrega: "01/2028",
    dorms: 2,
    condicao: "Financiamento Imediato ENTRADA ATÃ 82X DOC GRATIS",
    renda_ideal: "4700",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 21,
    nome: "ECO VIVA - VISTA BELA",
    incorporadora: "EMAIS",
    regiao: "OESTE",
    m2: 49.9,
    valor: 251170,
    valor_avaliacao: 264000,
    entrega: "11/2027",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "4500",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 22,
    nome: "ECO VIVA - MAIS PARQUE",
    incorporadora: "EMAIS",
    regiao: "LESTE",
    m2: 55.2,
    valor: 247500,
    valor_avaliacao: 264000,
    entrega: "11/2027",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "4500",
    categoria: "mcmv",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  // Category 2: Repasse Imediato | Outros (mid/high)
  {
    id: 23,
    nome: "TORRES CIDADE NORTE",
    incorporadora: "RVE",
    regiao: "NORTE",
    m2: 51.7,
    valor: 301000,
    valor_avaliacao: 321000,
    entrega: "02/2026",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 24,
    nome: "PALESTRA LIFE",
    incorporadora: "INC",
    regiao: "OESTE",
    m2: 50.4,
    valor: 274900,
    valor_avaliacao: 349299,
    entrega: "03/2027",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 25,
    nome: "PALESTRA LIFE",
    incorporadora: "INC",
    regiao: "OESTE",
    m2: 50.8,
    valor: 259900,
    valor_avaliacao: 351035,
    entrega: "04/2027",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 26,
    nome: "TREND",
    incorporadora: "LONGITUDE",
    regiao: "NORTE",
    m2: 64.0,
    valor: 300070,
    valor_avaliacao: 299000,
    entrega: "01/2028",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 27,
    nome: "BLISS OÃSIS",
    incorporadora: "CITZ",
    regiao: "NORTE",
    m2: 49.0,
    valor: 321339,
    valor_avaliacao: 327000,
    entrega: "12/2026",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 28,
    nome: "VALLE DOS COLIBIRIS",
    incorporadora: "VITTA",
    regiao: "NORTE",
    m2: 47.9,
    valor: 255000,
    valor_avaliacao: 315300,
    entrega: "01/2027",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 29,
    nome: "VALLE DOS COLIBIRIS",
    incorporadora: "VITTA",
    regiao: "NORTE",
    m2: 46.7,
    valor: 255000,
    valor_avaliacao: 315300,
    entrega: "01/2027",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 30,
    nome: "VALLE DOS COLIBIRIS",
    incorporadora: "VITTA",
    regiao: "NORTE",
    m2: 48.1,
    valor: 255000,
    valor_avaliacao: 315300,
    entrega: "01/2027",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 31,
    nome: "NOVA SMART 1Âª FASE",
    incorporadora: "RVE",
    regiao: "LESTE",
    m2: 52.4,
    valor: 305000,
    valor_avaliacao: 381000,
    entrega: "08/2026",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 32,
    nome: "NOVA SMART 1Âª FASE",
    incorporadora: "RVE",
    regiao: "LESTE",
    m2: 54.1,
    valor: 297000,
    valor_avaliacao: 387000,
    entrega: "09/2026",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 33,
    nome: "TRINITA",
    incorporadora: "VITTA",
    regiao: "LESTE",
    m2: 49.7,
    valor: 340000,
    valor_avaliacao: null,
    entrega: "04/2026",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 34,
    nome: "BLISS OÃSIS",
    incorporadora: "CITZ",
    regiao: "NORTE",
    m2: 56.9,
    valor: 320310,
    valor_avaliacao: 353850,
    entrega: "12/2026",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 35,
    nome: "PALESTRA LIFE",
    incorporadora: "INC",
    regiao: "OESTE",
    m2: 79.8,
    valor: 443804,
    valor_avaliacao: 443804,
    entrega: "04/2027",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "12000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 36,
    nome: "NOVA SMART 3Âª FASE",
    incorporadora: "RVE",
    regiao: "LESTE",
    m2: 52.4,
    valor: 307000,
    valor_avaliacao: 343000,
    entrega: "11/2027",
    dorms: null,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 37,
    nome: "NOVA SMART 3Âª FASE",
    incorporadora: "RVE",
    regiao: "LESTE",
    m2: 54.1,
    valor: 307000,
    valor_avaliacao: 340000,
    entrega: "11/2027",
    dorms: null,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 38,
    nome: "NOVA SMART 2Âª FASE",
    incorporadora: "RVE",
    regiao: "LESTE",
    m2: 52.4,
    valor: 305000,
    valor_avaliacao: 391000,
    entrega: "06/2026",
    dorms: null,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 39,
    nome: "NOVA SMART 2Âª FASE",
    incorporadora: "RVE",
    regiao: "LESTE",
    m2: 54.1,
    valor: 305000,
    valor_avaliacao: 387000,
    entrega: "06/2027",
    dorms: null,
    condicao: "Financiamento Imediato",
    renda_ideal: "8000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 40,
    nome: "PIAVON",
    incorporadora: "FAJ",
    regiao: "NORTE",
    m2: 39.0,
    valor: 219900,
    valor_avaliacao: 237000,
    entrega: null,
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "4000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 41,
    nome: "UPSIDE",
    incorporadora: "INC",
    regiao: "LESTE",
    m2: 100,
    valor: 549900,
    valor_avaliacao: 642000,
    entrega: "08/2025",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 42,
    nome: "BLISS OÃSIS",
    incorporadora: "CITZ",
    regiao: "NORTE",
    m2: 68.3,
    valor: 453200,
    valor_avaliacao: 424200,
    entrega: "12/2026",
    dorms: 3,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  // Category 3: Repasse Imediato | Outros (PSM IMÃVEIS) - higher value
  {
    id: 43,
    nome: "CASAS JD VERSALHES",
    incorporadora: "RNI",
    regiao: "BADY BASSIT",
    m2: 76.5,
    valor: 410000,
    valor_avaliacao: 521126,
    entrega: "ENTREGUE",
    dorms: 3,
    condicao: "Financiamento Imediato",
    renda_ideal: "9500",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 44,
    nome: "CASAS JD VERSALHES",
    incorporadora: "RNI",
    regiao: "BADY BASSIT",
    m2: 60.23,
    valor: 320000,
    valor_avaliacao: 401802,
    entrega: "ENTREGUE",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: "8800",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 45,
    nome: "CASAS JD VERSALHES",
    incorporadora: "RNI",
    regiao: "BADY BASSIT",
    m2: 77.5,
    valor: 480000,
    valor_avaliacao: 525993,
    entrega: "ENTREGUE",
    dorms: 3,
    condicao: "Financiamento Imediato",
    renda_ideal: "12000",
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 46,
    nome: "FENHOUSE",
    incorporadora: "FENHOUSE",
    regiao: "LESTE",
    m2: 88.0,
    valor: 480000,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 3,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 47,
    nome: "PARQUE LOMBARDIA",
    incorporadora: "MRV",
    regiao: "LESTE",
    m2: 92.3,
    valor: 620000,
    valor_avaliacao: 620000,
    entrega: "ENTREGUE",
    dorms: 3,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 48,
    nome: "SMART ONE",
    incorporadora: "FEX",
    regiao: "SUL",
    m2: 69.9,
    valor: 530000,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 49,
    nome: "HYPE 017",
    incorporadora: "GERETTI",
    regiao: "SUL",
    m2: 40.0,
    valor: 555500,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 1,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 50,
    nome: "RAIZES IMPPERIAL",
    incorporadora: "IMPPER",
    regiao: "BADY BASSIT",
    m2: 104.9,
    valor: 586700,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 51,
    nome: "MEET",
    incorporadora: "BILD",
    regiao: "SUL",
    m2: 48.0,
    valor: 486000,
    valor_avaliacao: 572882,
    entrega: "ENTREGUE",
    dorms: 1,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 52,
    nome: "RAIZES IMPPERIAL",
    incorporadora: "IMPPER",
    regiao: "BADY BASSIT",
    m2: 123.0,
    valor: 749524,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 3,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 53,
    nome: "RAIZES IMPPERIAL",
    incorporadora: "IMPPER",
    regiao: "BADY BASSIT",
    m2: 104,
    valor: 617242,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 54,
    nome: "MEET",
    incorporadora: "BILD",
    regiao: "SUL",
    m2: 67.5,
    valor: 612000,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 55,
    nome: "MEET",
    incorporadora: "BILD",
    regiao: "SUL",
    m2: 78.5,
    valor: 720356,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 3,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 56,
    nome: "GEORGINA BUSINESS PARK SETOR OCEANIA",
    incorporadora: "HDAUFF",
    regiao: "SUL",
    m2: 62.8,
    valor: 763300,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 57,
    nome: "MIRÃ JK",
    incorporadora: "LUPEMA",
    regiao: "SUL",
    m2: 71.8,
    valor: 829000,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 58,
    nome: "TERRACE",
    incorporadora: "LUPEMA",
    regiao: "SUL",
    m2: 81.7,
    valor: 884000,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 3,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 59,
    nome: "TIME",
    incorporadora: "GARETTI",
    regiao: "SUL",
    m2: 98.0,
    valor: 993000,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 3,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 60,
    nome: "TERRACE",
    incorporadora: "LUPEMA",
    regiao: "SUL",
    m2: 81.7,
    valor: 884000,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 3,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 61,
    nome: "TIME",
    incorporadora: "GARETTI",
    regiao: "SUL",
    m2: 98.0,
    valor: 993000,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 3,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 62,
    nome: "HUBLOT",
    incorporadora: "JRC",
    regiao: "SUL",
    m2: 48.0,
    valor: 419000,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 1,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 63,
    nome: "TERRACE RESIDENCE",
    incorporadora: "LUPEMA",
    regiao: "SUL",
    m2: 81.73,
    valor: 930240,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: 2,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 64,
    nome: "PLAZA CORPORATE",
    incorporadora: "GARETTI",
    regiao: "SUL",
    m2: 60.0,
    valor: 652020,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: null,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 65,
    nome: "PÃTIO PITANGUEIRAS",
    incorporadora: "HUGO ENGENHARIA",
    regiao: "SUL",
    m2: 94.4,
    valor: 1002200,
    valor_avaliacao: null,
    entrega: "03/2026",
    dorms: 3,
    condicao: "Financiamento Imediato",
    renda_ideal: null,
    categoria: "outros",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  // Category 4: Start | Repasse Futuro (PSM IMÃVEIS)
  {
    id: 66,
    nome: "OLYMPEA",
    incorporadora: "JRC",
    regiao: "SUL",
    m2: 61.78,
    valor: 518700,
    valor_avaliacao: null,
    entrega: "07/2029",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "30/70",
    ato: "6%",
    meses_restantes: 40
  },
  {
    id: 67,
    nome: "QUINTA DAS AMORAS",
    incorporadora: "TARRAF",
    regiao: "LESTE",
    m2: 46.0,
    valor: 264500,
    valor_avaliacao: null,
    entrega: "08/2027",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "20/80",
    ato: "7.2%",
    meses_restantes: 17
  },
  {
    id: 68,
    nome: "PLATZ BY TARRAF",
    incorporadora: "TARRAF",
    regiao: "SUL",
    m2: 27.0,
    valor: 413800,
    valor_avaliacao: null,
    entrega: "03/2026+180dias",
    dorms: 1,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: 4
  },
  {
    id: 69,
    nome: "QUINTA DAS AMORAS",
    incorporadora: "TARRAF",
    regiao: "LESTE",
    m2: 52.0,
    valor: 391686,
    valor_avaliacao: null,
    entrega: "08/2027",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "20/80",
    ato: "7.2%",
    meses_restantes: 17
  },
  {
    id: 70,
    nome: "CONNECT IMPPER",
    incorporadora: "IMPPER",
    regiao: "CENTRAL",
    m2: 58.3,
    valor: 470460,
    valor_avaliacao: null,
    entrega: "03/2027",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "20/80",
    ato: "7%",
    meses_restantes: 11
  },
  {
    id: 71,
    nome: "CONNECT IMPPER",
    incorporadora: "IMPPER",
    regiao: "CENTRAL",
    m2: 54.1,
    valor: 420110,
    valor_avaliacao: null,
    entrega: "02/2027",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "20/80",
    ato: "7%",
    meses_restantes: 11
  },
  {
    id: 72,
    nome: "VIBE RESIDENCE",
    incorporadora: "GARETTI",
    regiao: "SUL",
    m2: 40.0,
    valor: 439053,
    valor_avaliacao: null,
    entrega: "08/2026",
    dorms: 1,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "20/80",
    ato: "10%",
    meses_restantes: 3
  },
  {
    id: 73,
    nome: "CONNECT IMPPER",
    incorporadora: "IMPPER",
    regiao: "CENTRAL",
    m2: 64.4,
    valor: 501533,
    valor_avaliacao: null,
    entrega: "03/2027",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "20/80",
    ato: "7%",
    meses_restantes: 11
  },
  {
    id: 74,
    nome: "IPANEMA PRAIAS",
    incorporadora: "TARRAF",
    regiao: "SUL",
    m2: 41.0,
    valor: 483664,
    valor_avaliacao: null,
    entrega: "07/2026",
    dorms: 1,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "20/80",
    ato: "6%",
    meses_restantes: 10
  },
  {
    id: 75,
    nome: "CONNECT IMPPER",
    incorporadora: "IMPPER",
    regiao: "CENTRAL",
    m2: 66.3,
    valor: 516330,
    valor_avaliacao: null,
    entrega: "03/2027",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "20/80",
    ato: "7%",
    meses_restantes: 11
  },
  {
    id: 76,
    nome: "CUBO 123",
    incorporadora: "GARETTI",
    regiao: "SUL",
    m2: 35.0,
    valor: 451564,
    valor_avaliacao: null,
    entrega: "02/2027",
    dorms: 1,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "25/75",
    ato: "7%",
    meses_restantes: 11
  },
  {
    id: 77,
    nome: "SKY REDENTORA",
    incorporadora: "STEPHANNIE NOGUEIRA",
    regiao: "CENTRAL",
    m2: 63.9,
    valor: 506780,
    valor_avaliacao: null,
    entrega: "11/2029",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "25/75",
    ato: "9%",
    meses_restantes: 44
  },
  {
    id: 78,
    nome: "SKY REDENTORA",
    incorporadora: "STEPHANNIE NOGUEIRA",
    regiao: "CENTRAL",
    m2: 82.23,
    valor: 646810,
    valor_avaliacao: null,
    entrega: "11/2029",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "25/75",
    ato: "9%",
    meses_restantes: 44
  },
  {
    id: 79,
    nome: "SKY REDENTORA",
    incorporadora: "STEPHANNIE NOGUEIRA",
    regiao: "CENTRAL",
    m2: 122.48,
    valor: 788292,
    valor_avaliacao: null,
    entrega: "11/2029",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "25/75",
    ato: "9%",
    meses_restantes: 44
  },
  {
    id: 80,
    nome: "PLATZ BY TARRAF",
    incorporadora: "TARRAF",
    regiao: "SUL",
    m2: 35.0,
    valor: 470000,
    valor_avaliacao: null,
    entrega: "03/2026+180DIAS",
    dorms: 1,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: null,
    ato: null,
    meses_restantes: 4
  },
  {
    id: 81,
    nome: "JAZZ RESIDENCIAL",
    incorporadora: "KARVAS",
    regiao: "SUL",
    m2: 67.3,
    valor: 541000,
    valor_avaliacao: null,
    entrega: "09/2026",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "30/70",
    ato: "10%",
    meses_restantes: 7
  },
  {
    id: 82,
    nome: "JAZZ RESIDENCIAL",
    incorporadora: "KARVAS",
    regiao: "SUL",
    m2: 69.0,
    valor: 563000,
    valor_avaliacao: null,
    entrega: "09/2026",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "30/70",
    ato: "10%",
    meses_restantes: 7
  },
  {
    id: 83,
    nome: "SINNI 551",
    incorporadora: "LUPEMA",
    regiao: "SUL",
    m2: 58.5,
    valor: 567200,
    valor_avaliacao: null,
    entrega: "08/2029",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "43/57",
    ato: "5%",
    meses_restantes: 41
  },
  {
    id: 84,
    nome: "THE CITY",
    incorporadora: "BILD",
    regiao: "LESTE",
    m2: 34.06,
    valor: 511347,
    valor_avaliacao: null,
    entrega: "02/2029",
    dorms: null,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "30/70",
    ato: "6%",
    meses_restantes: 35
  },
  {
    id: 85,
    nome: "VIVEN",
    incorporadora: "BILD",
    regiao: "SUL",
    m2: 59.95,
    valor: 555071,
    valor_avaliacao: null,
    entrega: "10/2027",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "25/75",
    ato: "8%",
    meses_restantes: 19
  },
  {
    id: 86,
    nome: "THE CITY",
    incorporadora: "BILD",
    regiao: "LESTE",
    m2: 36.36,
    valor: 535192,
    valor_avaliacao: null,
    entrega: "02/2029",
    dorms: null,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "30/70",
    ato: "6%",
    meses_restantes: 35
  },
  {
    id: 87,
    nome: "PALESTRA LIFE",
    incorporadora: "INC",
    regiao: "OESTE",
    m2: 100.4,
    valor: 541520,
    valor_avaliacao: null,
    entrega: "04/2027",
    dorms: 3,
    condicao: "Repasse Imediato",
    renda_ideal: null,
    categoria: "start",
    tipo: "repasse_imediato",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: 13
  },
  // Category 5: Plus | Repasse Futuro
  {
    id: 88,
    nome: "BOULEVARD TOWERS",
    incorporadora: "HUGO",
    regiao: "SUL",
    m2: 69.0,
    valor: 595340,
    valor_avaliacao: null,
    entrega: "06/2027",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "25/75",
    ato: "6%",
    meses_restantes: 15
  },
  {
    id: 89,
    nome: "LINE SEGUNDA FASE",
    incorporadora: "IMPPER",
    regiao: "LESTE",
    m2: 108.0,
    valor: 636303,
    valor_avaliacao: null,
    entrega: "04/2029",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "25/75",
    ato: "5%",
    meses_restantes: 37
  },
  {
    id: 90,
    nome: "VIVEN",
    incorporadora: "BILD",
    regiao: "SUL",
    m2: 69.4,
    valor: 653153,
    valor_avaliacao: null,
    entrega: "04/2027",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "25/75",
    ato: "8%",
    meses_restantes: 19
  },
  {
    id: 91,
    nome: "SINNI 551",
    incorporadora: "LUPEMA",
    regiao: "SUL",
    m2: 65.5,
    valor: 607200,
    valor_avaliacao: null,
    entrega: "08/2029",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "43/57",
    ato: "5%",
    meses_restantes: 41
  },
  {
    id: 92,
    nome: "MATIZ",
    incorporadora: "HUGO FABRI",
    regiao: "SUL",
    m2: 75.0,
    valor: 780000,
    valor_avaliacao: null,
    entrega: "06/2029",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "30/70",
    ato: "5%",
    meses_restantes: 41
  },
  {
    id: 93,
    nome: "MATIZ",
    incorporadora: "HUGO FABRI",
    regiao: "SUL",
    m2: 66.0,
    valor: 626000,
    valor_avaliacao: null,
    entrega: "06/2029",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "30/70",
    ato: "5%",
    meses_restantes: 41
  },
  {
    id: 94,
    nome: "JAZZ RESIDENCIAL",
    incorporadora: "KARVAS",
    regiao: "SUL",
    m2: 80.0,
    valor: 704000,
    valor_avaliacao: null,
    entrega: "09/2026",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "30/70",
    ato: "10%",
    meses_restantes: 7
  },
  {
    id: 95,
    nome: "BOULEVARD TOWERS",
    incorporadora: "HUGO",
    regiao: "SUL",
    m2: 73.0,
    valor: 814678,
    valor_avaliacao: null,
    entrega: "06/2027",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "25/75",
    ato: "6%",
    meses_restantes: 15
  },
  {
    id: 96,
    nome: "SINNI 551",
    incorporadora: "LUPEMA",
    regiao: "SUL",
    m2: 81.5,
    valor: 725800,
    valor_avaliacao: null,
    entrega: "08/2029",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "43/57",
    ato: "5%",
    meses_restantes: 41
  },
  {
    id: 97,
    nome: "VERSO JK",
    incorporadora: "LUPEMA",
    regiao: "SUL",
    m2: 66.7,
    valor: 689000,
    valor_avaliacao: null,
    entrega: "11/2026",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "26.5/73.5",
    ato: "5%",
    meses_restantes: 8
  },
  {
    id: 98,
    nome: "INFINITY",
    incorporadora: "TARRAF",
    regiao: "SUL",
    m2: 47.11,
    valor: 785960,
    valor_avaliacao: null,
    entrega: "07/2029",
    dorms: null,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "40/60",
    ato: "10%",
    meses_restantes: 40
  },
  {
    id: 99,
    nome: "INFINITY",
    incorporadora: "TARRAF",
    regiao: "SUL",
    m2: 43.0,
    valor: 734795,
    valor_avaliacao: null,
    entrega: "07/2029",
    dorms: null,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "40/60",
    ato: "10%",
    meses_restantes: 40
  },
  {
    id: 100,
    nome: "IPANEMA PRAIAS",
    incorporadora: "TARRAF",
    regiao: "SUL",
    m2: 67.6,
    valor: 629127,
    valor_avaliacao: null,
    entrega: "07/2026",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "20/80",
    ato: "6%",
    meses_restantes: 4
  },
  {
    id: 101,
    nome: "THE CITY",
    incorporadora: "BILD",
    regiao: "LESTE",
    m2: 48.0,
    valor: 735975,
    valor_avaliacao: null,
    entrega: "02/2029",
    dorms: null,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "30/70",
    ato: "6%",
    meses_restantes: 35
  },
  {
    id: 102,
    nome: "VERSO JK",
    incorporadora: "LUPEMA",
    regiao: "SUL",
    m2: 71.0,
    valor: 729900,
    valor_avaliacao: null,
    entrega: "11/2026",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "26.5/73.5",
    ato: "5%",
    meses_restantes: 8
  },
  {
    id: 103,
    nome: "LEGACY COMERCIAL",
    incorporadora: "IMPPER",
    regiao: "SUL",
    m2: 52.8,
    valor: 772530,
    valor_avaliacao: null,
    entrega: "09/2028",
    dorms: null,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "40/60",
    ato: "9%",
    meses_restantes: 30
  },
  {
    id: 104,
    nome: "GEORGINA BUSINESS SETOR AMERICA",
    incorporadora: "HDAUFF",
    regiao: "SUL",
    m2: 50.2,
    valor: 765625,
    valor_avaliacao: null,
    entrega: "06/2028",
    dorms: null,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "30/70",
    ato: "10%",
    meses_restantes: 27
  },
  {
    id: 105,
    nome: "PRIME",
    incorporadora: "IMPPER",
    regiao: "LESTE",
    m2: 132.88,
    valor: 792690,
    valor_avaliacao: null,
    entrega: "01/2029",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "25/75",
    ato: "5%",
    meses_restantes: 34
  },
  {
    id: 106,
    nome: "BOULEVARD TOWERS",
    incorporadora: "HUGO",
    regiao: "SUL",
    m2: 82.5,
    valor: 785735,
    valor_avaliacao: null,
    entrega: "06/2027",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "25/75",
    ato: "6%",
    meses_restantes: 15
  },
  // Category 6: Plus | Repasse Futuro continued + higher
  {
    id: 107,
    nome: "VERSO JK",
    incorporadora: "LUPEMA",
    regiao: "SUL",
    m2: 86.6,
    valor: 879200,
    valor_avaliacao: null,
    entrega: "11/2026",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "26.5/73.5",
    ato: "5%",
    meses_restantes: 8
  },
  {
    id: 108,
    nome: "VIVEN",
    incorporadora: "BILD",
    regiao: "SUL",
    m2: 95.8,
    valor: 875397,
    valor_avaliacao: null,
    entrega: "04/2027",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "25/75",
    ato: "8%",
    meses_restantes: 19
  },
  {
    id: 109,
    nome: "LEGACY",
    incorporadora: "IMPPER",
    regiao: "SUL",
    m2: 84.0,
    valor: 913828,
    valor_avaliacao: null,
    entrega: "09/2028",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "1",
    fluxo: "25/75",
    ato: "7%",
    meses_restantes: 30
  },
  {
    id: 110,
    nome: "LEGACY",
    incorporadora: "IMPPER",
    regiao: "SUL",
    m2: 104.0,
    valor: 1058000,
    valor_avaliacao: null,
    entrega: "09/2028",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "25/75",
    ato: "77%",
    meses_restantes: 30
  },
  {
    id: 111,
    nome: "CUBO 123",
    incorporadora: "GARETTI",
    regiao: "SUL",
    m2: 70.0,
    valor: 903128,
    valor_avaliacao: null,
    entrega: "02/2027",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "25/75",
    ato: "7%",
    meses_restantes: 11
  },
  {
    id: 112,
    nome: "COPACABANA",
    incorporadora: "TARRAF",
    regiao: "SUL",
    m2: 103.2,
    valor: 1061068,
    valor_avaliacao: null,
    entrega: "06/2026",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "20/80",
    ato: "6%",
    meses_restantes: 3
  },
  {
    id: 113,
    nome: "HORIZON",
    incorporadora: "LUPEMA",
    regiao: "SUL",
    m2: 87.0,
    valor: 939000,
    valor_avaliacao: null,
    entrega: "07/2029",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "30/70",
    ato: "5%",
    meses_restantes: 40
  },
  {
    id: 114,
    nome: "RESERVA IMPERIAL",
    incorporadora: "IMPPER",
    regiao: "MIRASSOL",
    m2: 140.1,
    valor: 813192,
    valor_avaliacao: null,
    entrega: "10/2026",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "20/80",
    ato: "5%",
    meses_restantes: 7
  },
  {
    id: 115,
    nome: "VIVEN",
    incorporadora: "BILD",
    regiao: "SUL",
    m2: 85.4,
    valor: 817712,
    valor_avaliacao: null,
    entrega: "04/2027",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "plus",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "25/75",
    ato: "8%",
    meses_restantes: 19
  },
  // Category 7: Premium | Repasse Futuro
  {
    id: 116,
    nome: "LEGACY COMERCIAL",
    incorporadora: "IMPPER",
    regiao: "SUL",
    m2: 85.0,
    valor: 1223000,
    valor_avaliacao: null,
    entrega: "08/2028",
    dorms: null,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "premium",
    tipo: "repasse_futuro",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 117,
    nome: "CUBO 123",
    incorporadora: "GARETTI",
    regiao: "SUL",
    m2: 105.0,
    valor: 1317900,
    valor_avaliacao: null,
    entrega: "02/2027",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "premium",
    tipo: "repasse_futuro",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 118,
    nome: "MONREAL",
    incorporadora: "TARRAF",
    regiao: "SUL",
    m2: 140.0,
    valor: 1509650,
    valor_avaliacao: null,
    entrega: "03/2026",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "premium",
    tipo: "repasse_futuro",
    vagas: "2",
    fluxo: "14.1/85.9",
    ato: "6%",
    meses_restantes: 5
  },
  {
    id: 119,
    nome: "LEGACY COMERCIAL",
    incorporadora: "IMPPER",
    regiao: "SUL",
    m2: 119.0,
    valor: 1992000,
    valor_avaliacao: null,
    entrega: "08/2028",
    dorms: null,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "premium",
    tipo: "repasse_futuro",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 120,
    nome: "LEGACY COMERCIAL",
    incorporadora: "IMPPER",
    regiao: "SUL",
    m2: 141.0,
    valor: 2030000,
    valor_avaliacao: null,
    entrega: "08/2028",
    dorms: null,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "premium",
    tipo: "repasse_futuro",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  // Category 8: Loteamentos & CondomÃ­nios
  {
    id: 121,
    nome: "LOTEAMENTO LAGO SUL 2",
    incorporadora: "HDAUFF",
    regiao: "BADY BASSIT",
    m2: 150.0,
    valor: 45000,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: null,
    condicao: "Direto com Incorporadora",
    renda_ideal: null,
    categoria: "loteamento",
    tipo: "loteamento",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 122,
    nome: "LOTEAMENTO LAGO SUL 1",
    incorporadora: "HDAUFF",
    regiao: "BADY BASSIT",
    m2: 150.0,
    valor: 45000,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: null,
    condicao: "Direto com Incorporadora",
    renda_ideal: null,
    categoria: "loteamento",
    tipo: "loteamento",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 123,
    nome: "LOTEAMENTO FLOR DO CAMPO",
    incorporadora: "UNICOS",
    regiao: "MIRASSOL",
    m2: 197.27,
    valor: 67711,
    valor_avaliacao: null,
    entrega: null,
    dorms: null,
    condicao: "Direto com Incorporadora",
    renda_ideal: null,
    categoria: "loteamento",
    tipo: "loteamento",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 124,
    nome: "LOTEAMENTO LAGO SUL 2",
    incorporadora: "HDAUFF",
    regiao: "BADY BASSIT",
    m2: 246.0,
    valor: 73800,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: null,
    condicao: "Direto com Incorporadora",
    renda_ideal: null,
    categoria: "loteamento",
    tipo: "loteamento",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 125,
    nome: "LOTEAMENTO FLOR DO CAMPO",
    incorporadora: "UNICOS",
    regiao: "MIRASSOL",
    m2: 200.0,
    valor: 79930,
    valor_avaliacao: null,
    entrega: null,
    dorms: null,
    condicao: "Direto com Incorporadora",
    renda_ideal: null,
    categoria: "loteamento",
    tipo: "loteamento",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 126,
    nome: "LOTEAMENTO VILA PARECIS",
    incorporadora: "FAJ",
    regiao: "OESTE",
    m2: 200.0,
    valor: 80000,
    valor_avaliacao: null,
    entrega: null,
    dorms: null,
    condicao: "Direto com Incorporadora",
    renda_ideal: null,
    categoria: "loteamento",
    tipo: "loteamento",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 127,
    nome: "MONTECRISTO",
    incorporadora: "UNICOS",
    regiao: "LESTE",
    m2: 206.0,
    valor: 119083,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: null,
    condicao: "Direto com Incorporadora",
    renda_ideal: null,
    categoria: "loteamento",
    tipo: "loteamento",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 128,
    nome: "BIOCITY CLUB",
    incorporadora: "UNICOS",
    regiao: "LESTE",
    m2: 264.0,
    valor: 241493,
    valor_avaliacao: null,
    entrega: "03/2027",
    dorms: null,
    condicao: "Direto com Incorporadora",
    renda_ideal: null,
    categoria: "loteamento",
    tipo: "loteamento",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 129,
    nome: "QUINTA DO LAGO 4 LAKE VICTORIA",
    incorporadora: "CONCRETIZA",
    regiao: "LESTE",
    m2: 300.0,
    valor: 229000,
    valor_avaliacao: null,
    entrega: null,
    dorms: null,
    condicao: "Direto com Incorporadora",
    renda_ideal: null,
    categoria: "loteamento",
    tipo: "loteamento",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 130,
    nome: "QUINTA DO LESTE",
    incorporadora: "UNICOS",
    regiao: "LESTE",
    m2: 200.0,
    valor: 92000,
    valor_avaliacao: null,
    entrega: null,
    dorms: null,
    condicao: "Direto com Incorporadora",
    renda_ideal: null,
    categoria: "loteamento",
    tipo: "loteamento",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 131,
    nome: "LE VERT",
    incorporadora: "CONCRETIZA",
    regiao: "SUL",
    m2: 405.0,
    valor: 697545,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: null,
    condicao: "Direto com Incorporadora",
    renda_ideal: null,
    categoria: "loteamento",
    tipo: "loteamento",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 132,
    nome: "HACIENDA ESMERALDA",
    incorporadora: "COSTANTINI",
    regiao: "SUL",
    m2: 407.4,
    valor: 977760,
    valor_avaliacao: null,
    entrega: "07/2028",
    dorms: null,
    condicao: "Direto com Incorporadora",
    renda_ideal: null,
    categoria: "loteamento",
    tipo: "loteamento",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 133,
    nome: "QUINTA DO GOLFE RESERVA",
    incorporadora: "HDAUFF",
    regiao: "SUL",
    m2: 494.4,
    valor: 1216800,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: null,
    condicao: "Direto com Incorporadora",
    renda_ideal: null,
    categoria: "loteamento",
    tipo: "loteamento",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  {
    id: 134,
    nome: "QUINTA DO GOLFE HORIZONTES",
    incorporadora: "HDAUFF",
    regiao: "SUL",
    m2: 1521.0,
    valor: 3744800,
    valor_avaliacao: null,
    entrega: "ENTREGUE",
    dorms: null,
    condicao: "Direto com Incorporadora",
    renda_ideal: null,
    categoria: "loteamento",
    tipo: "loteamento",
    vagas: null,
    fluxo: null,
    ato: null,
    meses_restantes: null
  },
  // Category 9: PrÃ©-LanÃ§amentos
  {
    id: 135,
    nome: "GIULIA BOULEVARD",
    incorporadora: "UNICOS",
    regiao: "OESTE",
    m2: 49,
    valor: 350000,
    valor_avaliacao: null,
    entrega: "MARÃO/26",
    dorms: 2,
    condicao: "Repasse Imediato",
    renda_ideal: null,
    categoria: "pre_lancamento",
    tipo: "repasse_imediato",
    vagas: 1,
    fluxo: null,
    ato: null,
    meses_restantes: 0
  },
  {
    id: 136,
    nome: "SOHO SQUARE",
    incorporadora: "FAJ INVEST",
    regiao: "SUL",
    m2: 32,
    valor: 269900,
    valor_avaliacao: null,
    entrega: "MARÃO/26",
    dorms: 1,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "pre_lancamento",
    tipo: "repasse_futuro",
    vagas: null,
    fluxo: "30/70",
    ato: "5%",
    meses_restantes: 0
  },
  {
    id: 137,
    nome: "ALAMEDA DOS IPÃS",
    incorporadora: "IMPPER",
    regiao: "BADY BASSIT",
    m2: 60,
    valor: 380000,
    valor_avaliacao: null,
    entrega: "ABRIL/26",
    dorms: 2,
    condicao: "Repasse Futuro e Imediato",
    renda_ideal: null,
    categoria: "pre_lancamento",
    tipo: "repasse_futuro",
    vagas: 2,
    fluxo: "20/80",
    ato: "5%",
    meses_restantes: 1
  },
  {
    id: 138,
    nome: "ALAMEDA DOS IPÃS",
    incorporadora: "IMPPER",
    regiao: "BADY BASSIT",
    m2: 70,
    valor: 480000,
    valor_avaliacao: null,
    entrega: "ABRIL/26",
    dorms: 2,
    condicao: "Repasse Futuro e Imediato",
    renda_ideal: null,
    categoria: "pre_lancamento",
    tipo: "repasse_futuro",
    vagas: 2,
    fluxo: "20/80",
    ato: "5%",
    meses_restantes: 1
  },
  {
    id: 139,
    nome: "CASA PIETRA",
    incorporadora: "IMPPER",
    regiao: "SUL",
    m2: 174.71,
    valor: 1400000,
    valor_avaliacao: null,
    entrega: "MAIO/26",
    dorms: 3,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "pre_lancamento",
    tipo: "repasse_futuro",
    vagas: 2,
    fluxo: "20/80",
    ato: "5%",
    meses_restantes: 2
  },
  {
    id: 140,
    nome: "ORGANIQUE",
    incorporadora: "CITZ",
    regiao: "LESTE",
    m2: 49,
    valor: 350000,
    valor_avaliacao: null,
    entrega: "MAIO/26",
    dorms: 2,
    condicao: "Repasse Futuro",
    renda_ideal: null,
    categoria: "pre_lancamento",
    tipo: "repasse_futuro",
    vagas: 1,
    fluxo: "30/70",
    ato: "5%",
    meses_restantes: 2
  }
];

function filterProperties(query) {
  let filtered = properties;

  if (query.regiao) {
    filtered = filtered.filter(p => p.regiao?.toUpperCase() === query.regiao.toUpperCase());
  }

  if (query.dorms !== undefined) {
    const dorms = parseInt(query.dorms);
    filtered = filtered.filter(p => p.dorms === dorms);
  }

  if (query.valor_min !== undefined) {
    const min = parseInt(query.valor_min);
    filtered = filtered.filter(p => p.valor >= min);
  }

  if (query.valor_max !== undefined) {
    const max = parseInt(query.valor_max);
    filtered = filtered.filter(p => p.valor <= max);
  }

  if (query.categoria) {
    filtered = filtered.filter(p => p.categoria === query.categoria.toLowerCase());
  }

  if (query.tipo) {
    filtered = filtered.filter(p => p.tipo === query.tipo.toLowerCase());
  }

  if (query.m2_min !== undefined) {
    const min = parseFloat(query.m2_min);
    filtered = filtered.filter(p => p.m2 && p.m2 >= min);
  }

  if (query.m2_max !== undefined) {
    const max = parseFloat(query.m2_max);
    filtered = filtered.filter(p => p.m2 && p.m2 <= max);
  }

  if (query.search) {
    const term = query.search.toLowerCase();
    filtered = filtered.filter(p =>
      p.nome.toLowerCase().includes(term) ||
      p.incorporadora.toLowerCase().includes(term)
    );
  }

  return filtered;
}

function recommendProperties(preferences) {
  let scored = properties.map(prop => {
    let score = 0;

    if (preferences.regiao && prop.regiao?.toUpperCase() === preferences.regiao.toUpperCase()) {
      score += 100;
    }

    if (preferences.dorms && prop.dorms === preferences.dorms) {
      score += 50;
    }

    if (preferences.budget_max && prop.valor <= preferences.budget_max) {
      score += 30;
    }

    if (preferences.budget_min && prop.valor >= preferences.budget_min) {
      score += 30;
    }

    if (preferences.categoria && prop.categoria === preferences.categoria) {
      score += 40;
    }

    if (preferences.tipo && prop.tipo === preferences.tipo) {
      score += 20;
    }

    if (preferences.vagas && prop.vagas && parseInt(prop.vagas) >= preferences.vagas) {
      score += 15;
    }

    return { ...prop, score };
  });

  return scored
    .filter(p => p.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 5)
    .map(({ score, ...p }) => p);
}

// Exports for agent.js integration
module.exports = handler;
module.exports.properties = properties;
module.exports.filterProperties = filterProperties;
module.exports.recommendProperties = recommendProperties;

function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,POST');
  res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token,X-Requested-With,Accept,Accept-Version,Content-Length,Content-MD5,Content-Type,Date,X-Api-Version');

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  const disclaimer = '*Valores sujeito a alteraÃ§Ã£o pela incorporadora. Ref: 03/2026';

  if (req.method === 'GET') {
    if (req.query.recommend) {
      const preferences = req.query.preferences ? JSON.parse(req.query.preferences) : req.query;
      const recommendations = recommendProperties(preferences);
      return res.status(200).json({
        success: true,
        count: recommendations.length,
        data: recommendations,
        disclaimer
      });
    }

    const filtered = filterProperties(req.query);
    return res.status(200).json({
      success: true,
      count: filtered.length,
      total_available: properties.length,
      data: filtered,
      disclaimer
    });
  }

  if (req.method === 'POST') {
    if (req.body.action === 'search') {
      const filtered = filterProperties(req.body.filters || {});
      return res.status(200).json({
        success: true,
        count: filtered.length,
        data: filtered,
        disclaimer
      });
    }

    if (req.body.action === 'recommend') {
      const recommendations = recommendProperties(req.body.preferences);
      return res.status(200).json({
        success: true,
        count: recommendations.length,
        data: recommendations,
        disclaimer
      });
    }
  }

  res.status(405).json({ error: 'Method not allowed' });
}
